name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main
      - name: setup Golang
        uses: actions/setup-go@v6
        with:
          go-version: '^1.25.0'
      - name: Install prerequisites
        run: |
          sudo apt install libvirt-dev
      - name: build and release
        run: |
          go version
          if [ ! -e *.mod ]; then
            go mod init ${GITHUB_REPOSITORY}
          fi
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Version=${GITHUB_REF_NAME} -X main.BuiltBy=github-actions" -o "libvirt-backup$(go env GOOS)-$(go env GOARCH)"
          execFile=$(find . -type f -executable -name 'libvirt-backup*')
          gh release create $tag \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --generate-notes
          gh release upload $tag $execFile
